# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/michael/coding/projects/ChessEngine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/michael/coding/projects/ChessEngine/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/michael/coding/projects/ChessEngine/build/CMakeFiles /home/michael/coding/projects/ChessEngine/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/michael/coding/projects/ChessEngine/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/michael/coding/projects/ChessEngine/build/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named generate_magics

# Build rule for target.
generate_magics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 generate_magics
.PHONY : generate_magics

# fast build rule for target.
generate_magics/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generate_magics.dir/build.make CMakeFiles/generate_magics.dir/build
.PHONY : generate_magics/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named perft

# Build rule for target.
perft: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 perft
.PHONY : perft

# fast build rule for target.
perft/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perft.dir/build.make CMakeFiles/perft.dir/build
.PHONY : perft/fast

#=============================================================================
# Target rules for targets named engine

# Build rule for target.
engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine
.PHONY : engine

# fast build rule for target.
engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/build
.PHONY : engine/fast

#=============================================================================
# Target rules for targets named doctest_with_main

# Build rule for target.
doctest_with_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 doctest_with_main
.PHONY : doctest_with_main

# fast build rule for target.
doctest_with_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/doctest-build/CMakeFiles/doctest_with_main.dir/build.make _deps/doctest-build/CMakeFiles/doctest_with_main.dir/build
.PHONY : doctest_with_main/fast

src/Bitboard.tests.o: src/Bitboard.tests.cpp.o
.PHONY : src/Bitboard.tests.o

# target to build an object file
src/Bitboard.tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Bitboard.tests.cpp.o
.PHONY : src/Bitboard.tests.cpp.o

src/Bitboard.tests.i: src/Bitboard.tests.cpp.i
.PHONY : src/Bitboard.tests.i

# target to preprocess a source file
src/Bitboard.tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Bitboard.tests.cpp.i
.PHONY : src/Bitboard.tests.cpp.i

src/Bitboard.tests.s: src/Bitboard.tests.cpp.s
.PHONY : src/Bitboard.tests.s

# target to generate assembly for a file
src/Bitboard.tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Bitboard.tests.cpp.s
.PHONY : src/Bitboard.tests.cpp.s

src/Magic_generation_util.tests.o: src/Magic_generation_util.tests.cpp.o
.PHONY : src/Magic_generation_util.tests.o

# target to build an object file
src/Magic_generation_util.tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Magic_generation_util.tests.cpp.o
.PHONY : src/Magic_generation_util.tests.cpp.o

src/Magic_generation_util.tests.i: src/Magic_generation_util.tests.cpp.i
.PHONY : src/Magic_generation_util.tests.i

# target to preprocess a source file
src/Magic_generation_util.tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Magic_generation_util.tests.cpp.i
.PHONY : src/Magic_generation_util.tests.cpp.i

src/Magic_generation_util.tests.s: src/Magic_generation_util.tests.cpp.s
.PHONY : src/Magic_generation_util.tests.s

# target to generate assembly for a file
src/Magic_generation_util.tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Magic_generation_util.tests.cpp.s
.PHONY : src/Magic_generation_util.tests.cpp.s

src/Move_generator.o: src/Move_generator.cpp.o
.PHONY : src/Move_generator.o

# target to build an object file
src/Move_generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Move_generator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perft.dir/build.make CMakeFiles/perft.dir/src/Move_generator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/Move_generator.cpp.o
.PHONY : src/Move_generator.cpp.o

src/Move_generator.i: src/Move_generator.cpp.i
.PHONY : src/Move_generator.i

# target to preprocess a source file
src/Move_generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Move_generator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perft.dir/build.make CMakeFiles/perft.dir/src/Move_generator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/Move_generator.cpp.i
.PHONY : src/Move_generator.cpp.i

src/Move_generator.s: src/Move_generator.cpp.s
.PHONY : src/Move_generator.s

# target to generate assembly for a file
src/Move_generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Move_generator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perft.dir/build.make CMakeFiles/perft.dir/src/Move_generator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/Move_generator.cpp.s
.PHONY : src/Move_generator.cpp.s

src/Move_generator.tests.o: src/Move_generator.tests.cpp.o
.PHONY : src/Move_generator.tests.o

# target to build an object file
src/Move_generator.tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Move_generator.tests.cpp.o
.PHONY : src/Move_generator.tests.cpp.o

src/Move_generator.tests.i: src/Move_generator.tests.cpp.i
.PHONY : src/Move_generator.tests.i

# target to preprocess a source file
src/Move_generator.tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Move_generator.tests.cpp.i
.PHONY : src/Move_generator.tests.cpp.i

src/Move_generator.tests.s: src/Move_generator.tests.cpp.s
.PHONY : src/Move_generator.tests.s

# target to generate assembly for a file
src/Move_generator.tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Move_generator.tests.cpp.s
.PHONY : src/Move_generator.tests.cpp.s

src/Position.tests.o: src/Position.tests.cpp.o
.PHONY : src/Position.tests.o

# target to build an object file
src/Position.tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Position.tests.cpp.o
.PHONY : src/Position.tests.cpp.o

src/Position.tests.i: src/Position.tests.cpp.i
.PHONY : src/Position.tests.i

# target to preprocess a source file
src/Position.tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Position.tests.cpp.i
.PHONY : src/Position.tests.cpp.i

src/Position.tests.s: src/Position.tests.cpp.s
.PHONY : src/Position.tests.s

# target to generate assembly for a file
src/Position.tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Position.tests.cpp.s
.PHONY : src/Position.tests.cpp.s

src/State.o: src/State.cpp.o
.PHONY : src/State.o

# target to build an object file
src/State.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/State.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perft.dir/build.make CMakeFiles/perft.dir/src/State.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/State.cpp.o
.PHONY : src/State.cpp.o

src/State.i: src/State.cpp.i
.PHONY : src/State.i

# target to preprocess a source file
src/State.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/State.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perft.dir/build.make CMakeFiles/perft.dir/src/State.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/State.cpp.i
.PHONY : src/State.cpp.i

src/State.s: src/State.cpp.s
.PHONY : src/State.s

# target to generate assembly for a file
src/State.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/State.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perft.dir/build.make CMakeFiles/perft.dir/src/State.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/State.cpp.s
.PHONY : src/State.cpp.s

src/State.tests.o: src/State.tests.cpp.o
.PHONY : src/State.tests.o

# target to build an object file
src/State.tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/State.tests.cpp.o
.PHONY : src/State.tests.cpp.o

src/State.tests.i: src/State.tests.cpp.i
.PHONY : src/State.tests.i

# target to preprocess a source file
src/State.tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/State.tests.cpp.i
.PHONY : src/State.tests.cpp.i

src/State.tests.s: src/State.tests.cpp.s
.PHONY : src/State.tests.s

# target to generate assembly for a file
src/State.tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/State.tests.cpp.s
.PHONY : src/State.tests.cpp.s

src/Transposition_table.tests.o: src/Transposition_table.tests.cpp.o
.PHONY : src/Transposition_table.tests.o

# target to build an object file
src/Transposition_table.tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Transposition_table.tests.cpp.o
.PHONY : src/Transposition_table.tests.cpp.o

src/Transposition_table.tests.i: src/Transposition_table.tests.cpp.i
.PHONY : src/Transposition_table.tests.i

# target to preprocess a source file
src/Transposition_table.tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Transposition_table.tests.cpp.i
.PHONY : src/Transposition_table.tests.cpp.i

src/Transposition_table.tests.s: src/Transposition_table.tests.cpp.s
.PHONY : src/Transposition_table.tests.s

# target to generate assembly for a file
src/Transposition_table.tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Transposition_table.tests.cpp.s
.PHONY : src/Transposition_table.tests.cpp.s

src/Uci_handler.o: src/Uci_handler.cpp.o
.PHONY : src/Uci_handler.o

# target to build an object file
src/Uci_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/Uci_handler.cpp.o
.PHONY : src/Uci_handler.cpp.o

src/Uci_handler.i: src/Uci_handler.cpp.i
.PHONY : src/Uci_handler.i

# target to preprocess a source file
src/Uci_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/Uci_handler.cpp.i
.PHONY : src/Uci_handler.cpp.i

src/Uci_handler.s: src/Uci_handler.cpp.s
.PHONY : src/Uci_handler.s

# target to generate assembly for a file
src/Uci_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/Uci_handler.cpp.s
.PHONY : src/Uci_handler.cpp.s

src/magic_main.o: src/magic_main.cpp.o
.PHONY : src/magic_main.o

# target to build an object file
src/magic_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generate_magics.dir/build.make CMakeFiles/generate_magics.dir/src/magic_main.cpp.o
.PHONY : src/magic_main.cpp.o

src/magic_main.i: src/magic_main.cpp.i
.PHONY : src/magic_main.i

# target to preprocess a source file
src/magic_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generate_magics.dir/build.make CMakeFiles/generate_magics.dir/src/magic_main.cpp.i
.PHONY : src/magic_main.cpp.i

src/magic_main.s: src/magic_main.cpp.s
.PHONY : src/magic_main.s

# target to generate assembly for a file
src/magic_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generate_magics.dir/build.make CMakeFiles/generate_magics.dir/src/magic_main.cpp.s
.PHONY : src/magic_main.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/perft_main.o: src/perft_main.cpp.o
.PHONY : src/perft_main.o

# target to build an object file
src/perft_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perft.dir/build.make CMakeFiles/perft.dir/src/perft_main.cpp.o
.PHONY : src/perft_main.cpp.o

src/perft_main.i: src/perft_main.cpp.i
.PHONY : src/perft_main.i

# target to preprocess a source file
src/perft_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perft.dir/build.make CMakeFiles/perft.dir/src/perft_main.cpp.i
.PHONY : src/perft_main.cpp.i

src/perft_main.s: src/perft_main.cpp.s
.PHONY : src/perft_main.s

# target to generate assembly for a file
src/perft_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perft.dir/build.make CMakeFiles/perft.dir/src/perft_main.cpp.s
.PHONY : src/perft_main.cpp.s

src/test_main.o: src/test_main.cpp.o
.PHONY : src/test_main.o

# target to build an object file
src/test_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/test_main.cpp.o
.PHONY : src/test_main.cpp.o

src/test_main.i: src/test_main.cpp.i
.PHONY : src/test_main.i

# target to preprocess a source file
src/test_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/test_main.cpp.i
.PHONY : src/test_main.cpp.i

src/test_main.s: src/test_main.cpp.s
.PHONY : src/test_main.s

# target to generate assembly for a file
src/test_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/test_main.cpp.s
.PHONY : src/test_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... doctest_with_main"
	@echo "... engine"
	@echo "... generate_magics"
	@echo "... perft"
	@echo "... tests"
	@echo "... src/Bitboard.tests.o"
	@echo "... src/Bitboard.tests.i"
	@echo "... src/Bitboard.tests.s"
	@echo "... src/Magic_generation_util.tests.o"
	@echo "... src/Magic_generation_util.tests.i"
	@echo "... src/Magic_generation_util.tests.s"
	@echo "... src/Move_generator.o"
	@echo "... src/Move_generator.i"
	@echo "... src/Move_generator.s"
	@echo "... src/Move_generator.tests.o"
	@echo "... src/Move_generator.tests.i"
	@echo "... src/Move_generator.tests.s"
	@echo "... src/Position.tests.o"
	@echo "... src/Position.tests.i"
	@echo "... src/Position.tests.s"
	@echo "... src/State.o"
	@echo "... src/State.i"
	@echo "... src/State.s"
	@echo "... src/State.tests.o"
	@echo "... src/State.tests.i"
	@echo "... src/State.tests.s"
	@echo "... src/Transposition_table.tests.o"
	@echo "... src/Transposition_table.tests.i"
	@echo "... src/Transposition_table.tests.s"
	@echo "... src/Uci_handler.o"
	@echo "... src/Uci_handler.i"
	@echo "... src/Uci_handler.s"
	@echo "... src/magic_main.o"
	@echo "... src/magic_main.i"
	@echo "... src/magic_main.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/perft_main.o"
	@echo "... src/perft_main.i"
	@echo "... src/perft_main.s"
	@echo "... src/test_main.o"
	@echo "... src/test_main.i"
	@echo "... src/test_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/michael/coding/projects/ChessEngine/build/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

