name: OpenBench Build
on:
  push:
  workflow_dispatch:

jobs:
  build_and_archive:
    name: Build and Archive
    strategy:
      matrix:
        os: [ubuntu-latest]
        nnue_flags: [avx2, avx512]
        cpu_flags: [popcnt, pext]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup Clang 18
      run: |
        wget -qO- https://apt.llvm.org/llvm.sh | bash -s -- 18
        sudo apt update
        sudo apt install -y clang-18
    - name: Clone Engine
      uses: actions/checkout@v4
    - name: Build Engine ${{ matrix.nnue_flags }}-${{ matrix.cpu_flags }}
      run: make EVALFILE=none CC=clang-18 static=1 ${{ matrix.nnue_flags }}=1 ${{ matrix.cpu_flags }}=1
    - name: Archive ${{ matrix.nnue_flags }}-${{ matrix.cpu_flags }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.sha }}-linux-${{ matrix.nnue_flags }}-${{ matrix.cpu_flags }}
        path: engine
