name: OpenBench Build
on:
  push:
  workflow_dispatch:

jobs:
  build_and_archive:
    name: Build and Archive
    runs-on: ubuntu-latest # No longer need matrix.os

    steps:
    - name: Setup Clang 18 and Libc++
      run: |
        wget -qO- https://apt.llvm.org/llvm.sh | sudo bash -s -- 18
        sudo apt update
        # Install both the compiler and the required standard library headers
        sudo apt install -y clang-18 libc++-18-dev
    - name: Clone Engine
      uses: actions/checkout@v4
    - name: Configure CMake with Clang
      run: |
        CC=clang-18 CXX=clang++-18 cmake -B build -DCMAKE_BUILD_TYPE=Release
    - name: Build Engine
      run: make -C build
    - name: Archive Build
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.sha }}-linux-engine
        path: build/engine
